language: php
php:
  - '7.3'
before_install:
  - make build
  - docker ps -a
services:
  - docker
install: composer
before_script:
  - cp .env.travis .env
script:
  - docker ps -a
  - docker exec -it arbitrage-web make generate-key
  - docker exec -it arbitrage-web make lint
  - sleep 15
  - docker exec -it arbitrage-web make migration
  - docker exec -it arbitrage-web make test
