language: php
php:
  - '7.3'
before_install:
  - make build
  - docker ps -a
services:
  - docker
before_script:
  - cp .env.travis .env
  - sudo /etc/init.d/postgresql stop
script:
  - docker ps -a
  - docker exec -it laravel-www make generate-key
  - docker exec -it laravel-www make lint
  - docker exec -it laravel-www make migration
  - docker exec -it laravel-www make test
